<a href="https://colab.research.google.com/github/meghanakolluri/Anime-Recommendation-System/blob/main/Content_based_anime_recommender.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import re
import seaborn as sns
%matplotlib inline

In [3]:
from google.colab import files
anime=files.upload()

Saving anime.csv to anime.csv


In [4]:
data=pd.read_csv('anime.csv')

In [5]:
data.head()

anime_id                              name  ... rating members
0     32281                    Kimi no Na wa.  ...   9.37  200630
1      5114  Fullmetal Alchemist: Brotherhood  ...   9.26  793665
2     28977                          Gintama°  ...   9.25  114262
3      9253                       Steins;Gate  ...   9.17  673572
4      9969                     Gintama&#039;  ...   9.16  151266

[5 rows x 7 columns]

In [6]:
data.shape

(12294, 7)

In [7]:
data.loc[(data["genre"]=="Hentai") & (data["episodes"]=="Unknown"),"episodes"] = "1"
data.loc[(data["type"]=="OVA") & (data["episodes"]=="Unknown"),"episodes"] = "1"

data.loc[(data["type"] == "Movie") & (data["episodes"] == "Unknown")] = "1"

In [8]:
df=data[data["episodes"]=="1"]
df

anime_id  ... members
0        32281  ...  200630
8        15335  ...   72534
11       28851  ...  102733
15         199  ...  466254
18       12355  ...  226193
...        ...  ...     ...
12288     5541  ...     166
12289     9316  ...     211
12290     5543  ...     183
12292     6133  ...     175
12293    26081  ...     142

[5731 rows x 7 columns]

In [9]:
known_animes = {"Naruto Shippuuden":500, "One Piece":784,"Detective Conan":854, "Dragon Ball Super":86,
                "Crayon Shin chan":942, "Yu Gi Oh Arc V":148,"Shingeki no Kyojin Season 2":25,
                "Boku no Hero Academia 2nd Season":25,"Little Witch Academia TV":25}

In [10]:
data

anime_id  ... members
0        32281  ...  200630
1         5114  ...  793665
2        28977  ...  114262
3         9253  ...  673572
4         9969  ...  151266
...        ...  ...     ...
12289     9316  ...     211
12290     5543  ...     183
12291     5621  ...     219
12292     6133  ...     175
12293    26081  ...     142

[12294 rows x 7 columns]

In [11]:
for k,v in known_animes.items():    
    data.loc[data["name"]==k,"episodes"] = v

In [12]:
data["episodes"] = data["episodes"].map(lambda x:np.nan if x=="Unknown" else x)

In [13]:
data["episodes"].fillna(data["episodes"].median(),inplace = True)

In [14]:
data["rating"] = data["rating"].astype(float)

In [15]:
data["rating"].fillna(data["rating"].median(),inplace = True)

In [16]:
pd.get_dummies(data[["type"]]).head()

type_1  type_Movie  type_Music  type_ONA  type_OVA  type_Special  type_TV
0       0           1           0         0         0             0        0
1       0           0           0         0         0             0        1
2       0           0           0         0         0             0        1
3       0           0           0         0         0             0        1
4       0           0           0         0         0             0        1

In [17]:
data["members"] = data["members"].astype(float)

In [18]:
anime_features = pd.concat([data["genre"].str.get_dummies(sep=","),
                            pd.get_dummies(data[["type"]]),data[["rating"]],
                            data[["members"]],data["episodes"]],axis=1)

In [19]:
data["name"] = data["name"].map(lambda name:re.sub('[^A-Za-z0-9]+', " ", name))

In [20]:
anime_features.head()

Adventure   Cars   Comedy   Dementia  ...  type_TV  rating   members  episodes
0           0      0        0          0  ...        0    9.37  200630.0         1
1           1      0        0          0  ...        1    9.26  793665.0        64
2           0      0        1          0  ...        1    9.25  114262.0        51
3           0      0        0          0  ...        1    9.17  673572.0        24
4           0      0        1          0  ...        1    9.16  151266.0        51

[5 rows x 93 columns]

In [21]:
anime_features.shape

(12294, 93)

In [22]:
anime_features.columns

Index([' Adventure', ' Cars', ' Comedy', ' Dementia', ' Demons', ' Drama',
       ' Ecchi', ' Fantasy', ' Game', ' Harem', ' Hentai', ' Historical',
       ' Horror', ' Josei', ' Kids', ' Magic', ' Martial Arts', ' Mecha',
       ' Military', ' Music', ' Mystery', ' Parody', ' Police',
       ' Psychological', ' Romance', ' Samurai', ' School', ' Sci-Fi',
       ' Seinen', ' Shoujo', ' Shoujo Ai', ' Shounen', ' Shounen Ai',
       ' Slice of Life', ' Space', ' Sports', ' Super Power', ' Supernatural',
       ' Thriller', ' Vampire', ' Yaoi', ' Yuri', '1', 'Action', 'Adventure',
       'Cars', 'Comedy', 'Dementia', 'Demons', 'Drama', 'Ecchi', 'Fantasy',
       'Game', 'Harem', 'Hentai', 'Historical', 'Horror', 'Josei', 'Kids',
       'Magic', 'Martial Arts', 'Mecha', 'Military', 'Music', 'Mystery',
       'Parody', 'Police', 'Psychological', 'Romance', 'Samurai', 'School',
       'Sci-Fi', 'Seinen', 'Shoujo', 'Shounen', 'Slice of Life', 'Space',
       'Sports', 'Super Power', 'Supernat

In [23]:
from sklearn.preprocessing import MaxAbsScaler

In [24]:
max_abs_scaler = MaxAbsScaler()
anime_features = max_abs_scaler.fit_transform(anime_features)

In [25]:
from sklearn.neighbors import NearestNeighbors
nbrs = NearestNeighbors(n_neighbors=6, algorithm='ball_tree').fit(anime_features)

In [26]:
distances, indices = nbrs.kneighbors(anime_features)
distances

array([[0.00000000e+00, 1.01506549e+00, 1.03095542e+00, 1.03102550e+00,
        1.41625771e+00, 1.43204444e+00],
       [0.00000000e+00, 1.02227158e+00, 1.49378838e+00, 1.51625674e+00,
        1.56476418e+00, 1.58623098e+00],
       [0.00000000e+00, 3.75894154e-02, 4.12559430e-02, 2.35028091e-01,
        2.87140333e-01, 1.41515906e+00],
       ...,
       [0.00000000e+00, 1.66436926e-03, 1.68253094e-03, 5.11962471e-03,
        6.22295696e-03, 6.22392854e-03],
       [0.00000000e+00, 1.00174940e-03, 1.10513608e-03, 2.00036985e-03,
        2.02599380e-03, 3.00064340e-03],
       [0.00000000e+00, 1.00000201e+00, 1.00001800e+00, 1.00001803e+00,
        1.00002450e+00, 1.00004050e+00]])

In [27]:
indices

array([[    0,   208,  1494,  1959,    60,  2103],
       [    1,   200,   268,   101,   795,   290],
       [    2,     4,     9,    12, 10896,     8],
       ...,
       [12291, 12238, 12237, 12236, 12256, 12235],
       [12292, 12231, 12232, 12230, 12229, 12283],
       [12293,  7426,  8279,  7349,  7335,  7498]])

In [28]:
def find(name):
    return data[data["name"]==name].index.tolist()[0]

In [29]:
find("Naruto")

841

In [30]:
distances[841]

array([0.        , 0.1906634 , 1.08585653, 1.4177656 , 1.44782088,
       1.47398665])

In [31]:
indices[841]

array([841, 615, 175, 582, 206, 178])

In [32]:
all_anime_names = list(data.name.values)

In [33]:
def get_id_from_partial_name(partial):
    for name in all_anime_names:
        if partial in name:
            print(name,all_anime_names.index(name))

In [34]:
def print_similar_animes(query=None,id=None):
    if id:
        print(id)
        for id in indices[id][1:]:
            print(data["name"].iloc[id])
    if query:
        found_id = find(query)
        for id in indices[found_id][1:]:
            print(data["name"].iloc[id])

In [35]:
print_similar_animes("Gintama")

Gintama 039 
Gintama 
Gintama 039 Enchousen
Gintama 2017 
Gintama Movie Kanketsu hen Yorozuya yo Eien Nare


In [36]:
print_similar_animes("Naruto")

Naruto Shippuuden
Katekyo Hitman Reborn 
Bleach
Dragon Ball Z
Boku no Hero Academia


In [37]:
print_similar_animes("Mushishi")

Mushishi Zoku Shou
Mushishi Zoku Shou 2nd Season
Mushishi Special Hihamukage
Mushishi Zoku Shou Odoro no Michi
Mushishi Zoku Shou Suzu no Shizuku


In [38]:
print_similar_animes("Kimi no Na wa ")

Kokoro ga Sakebitagatterunda 
Harmonie
Air Movie
Hotarubi no Mori e
Clannad Movie


In [39]:
print_similar_animes("Fairy Tail")

Fairy Tail 2014 
Magi The Labyrinth of Magic
Magi The Kingdom of Magic
Densetsu no Yuusha no Densetsu
Magi Sinbad no Bouken TV 
